### ISSUE TITLE
Small issues using it in a designer

### ISSUE THREAD

**Issue by jogibear9988** [smontanus/dial-gauge#1]
Hey I tried your NPM in my designer, and it worked. (https://node-projects.github.io/web-component-designer-demo/index.html)
But I've a few comments/additions,...

- How about adding the css with the ":host" selector, directly into the comontent? So the component has the css-properties defined, but the could be overriden when defined outside. So somone can see them directly in my designer (or also in the dev tools)
- the attributes section in the custom-elements.json is missing the link to the property, so my designer could not set the attributes. like here: https://github.com/node-projects/chart-js-webcomponent/blob/1277d1a3cc802c3cc0a755f27e97d1a36b42b135/custom-elements.json#L62
- You could use a AdoptedStylesheet, so you do not need a "style" tag in the dom, wich needs to be reparsed on each clone of the template.

**Comment by jogibear9988** [comment]
See usage in my designer here: https://node-projects.github.io/web-component-designer-demo/index.html?npm=dial-gauge&loadAllImports&html=%3Cdial-gauge%20value=%2250%22%20scale-start=%220%22%20scale-end=%22100%22%20style=%22width:200px;height:200px;position:absolute;left:211px;top:84px;%22%3E%3C/dial-gauge%3E

**Comment by jogibear9988** [comment]
One more issue: the custom-elements.json is missing in the npm package

**Comment by smontanus** [comment]
Resolved in your patch-1, patch-2, and patch-3 branches, along with a small syntax error fix from me.  All branches merged and included in version 0.1.4. Thanks for the help!

**Comment by jogibear9988** [comment]
I had one more typo in the package.json.
